### ISSUE TITLE
GitHub Desktop problem accessing .gitconfig

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/GitHub-guidance#2]
@J-Kamp had a problem cloning a repo and got this error message:

unable to access U://.gitconfig

Turned out to be permission/access problem.
I guess GitHub Desktop checks the configuration file whenever a repo is cloned.
Running GitHub Desktop as administrator eliminates the problem.
There might be a better solution, but I haven't found a simple way to change the location of the configuration file.
Probably it should be possible to change the Windows environment variable HOMEDIR and then reinstall GitHub Desktop.
See here for a bit more info: <https://stackoverflow.com/questions/25978057/where-to-find-create-git-config-file-for-local-configuration-for-project>.

**Comment by JohannaPedersen** [comment]
Is the info in the README file? Then we could maybe close the issue?

**Comment by sashahafner** [comment]
Yup, in https://github.com/AU-BCE-EE/GitHub-guidance/blob/main/github-desktop.md
Sure, closing!
